### ISSUE TITLE
Failed to Build

### ISSUE THREAD

**Issue by MrDrache333** [Nriver/anki-web-server-docker#2]
```
> docker-compose up -d
Building ankisyncserver
[+] Building 0.7s (9/13)                                                                                                  
 => [internal] load build definition from Dockerfile                                                                 0.0s
 => => transferring dockerfile: 37B                                                                                  0.0s
 => [internal] load .dockerignore                                                                                    0.0s
 => => transferring context: 2B                                                                                      0.0s
 => [internal] load metadata for docker.io/library/python:3.8                                                        0.6s
 => [1/9] FROM docker.io/library/python:3.8@sha256:c0fd64027a833c0caaf950ff6e4480d7cc1595991d9824f1114cd35765772b36  0.0s
 => [internal] load build context                                                                                    0.0s
 => => transferring context: 552B                                                                                    0.0s
 => CACHED [2/9] RUN echo "init anki-sync-server"                                                                    0.0s
 => CANCELED [3/9] ADD ankisyncd /app/ankisyncd                                                                      0.0s
 => ERROR [4/9] ADD utils /app/utils                                                                                 0.0s
 => ERROR [5/9] ADD ankisyncctl.py /app/ankisyncctl.py                                                               0.0s
------
 > [4/9] ADD utils /app/utils:
------
------
 > [5/9] ADD ankisyncctl.py /app/ankisyncctl.py:
------
failed to compute cache key: "/ankisyncctl.py" not found: not found
ERROR: Service 'ankisyncserver' failed to build : Build failed
```

System: macOS Montery, iMac with Intel CPU

How to Reproduce:
1. Clone Repo
2. Execute ./init.sh in cloned repo
3. Execute docker-compose up -d

**Comment by Nriver** [comment]
The upstream repo anki-snyc-server has changed their code, I will update my code to fix that.

However, I also find that they have commited some code that not fully tested and break their code. I will try to make a usable fork later.

**Comment by MrDrache333** [comment]
Thank you. Could you provide a Version number for those repos that gonna work with yours?

**Comment by Nriver** [comment]
You can go to anki-sync-server folder and get this specific [commit](https://github.com/ankicommunity/anki-sync-server/commit/43f4934de8add5f23aa9318a84c756f27214fb72) I am using.
```
git checkout 43f4934de8add5f23aa9318a84c756f27214fb72
```

Go to the docker-compose file, and rebuild the docker image then start
```
docker-compose build
docker-compose up
```

**Comment by Nriver** [comment]
Anki version number is 2.1.40

**Comment by bootymcjudy** [comment]
Hey Nriver,

I followed the instructions and the build was successful but when I run the compose file it seems like the anki-web-server container runs into issues and constantly reboots,

```
anki-web-server-docker-ankiwebserver-1 | More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
anki-web-server-docker-ankiwebserver-1 | Traceback (most recent call last):
anki-web-server-docker-ankiwebserver-1 |   File "app.py", line 6, in <module>
anki-web-server-docker-ankiwebserver-1 |     from flaskbp import create_app
anki-web-server-docker-ankiwebserver-1 |   File "/app/flaskbp/__init__.py", line 4, in <module>
anki-web-server-docker-ankiwebserver-1 |     from flaskbp.api.card import api_card
anki-web-server-docker-ankiwebserver-1 |   File "/app/flaskbp/api/card.py", line 7, in <module>
anki-web-server-docker-ankiwebserver-1 |     from flaskbp.utils.db_tool import get_collection
anki-web-server-docker-ankiwebserver-1 |   File "/app/flaskbp/utils/db_tool.py", line 4, in <module>
anki-web-server-docker-ankiwebserver-1 |     from anki import Collection
anki-web-server-docker-ankiwebserver-1 |   File "/usr/local/lib/python3.8/site-packages/anki/__init__.py", line 8, in <module>
anki-web-server-docker-ankiwebserver-1 |     from anki.collection import Collection
anki-web-server-docker-ankiwebserver-1 |   File "/usr/local/lib/python3.8/site-packages/anki/collection.py", line 15, in <module>
anki-web-server-docker-ankiwebserver-1 |     import anki.find
anki-web-server-docker-ankiwebserver-1 |   File "/usr/local/lib/python3.8/site-packages/anki/find.py", line 8, in <module>
anki-web-server-docker-ankiwebserver-1 |     from anki.hooks import *
anki-web-server-docker-ankiwebserver-1 |   File "/usr/local/lib/python3.8/site-packages/anki/hooks.py", line 20, in <module>
anki-web-server-docker-ankiwebserver-1 |     from anki.hooks_gen import *
anki-web-server-docker-ankiwebserver-1 |   File "/usr/local/lib/python3.8/site-packages/anki/hooks_gen.py", line 9, in <module>
anki-web-server-docker-ankiwebserver-1 |     from anki.cards import Card
anki-web-server-docker-ankiwebserver-1 |   File "/usr/local/lib/python3.8/site-packages/anki/cards.py", line 12, in <module>
anki-web-server-docker-ankiwebserver-1 |     from anki.consts import *
anki-web-server-docker-ankiwebserver-1 |   File "/usr/local/lib/python3.8/site-packages/anki/consts.py", line 9, in <module>
anki-web-server-docker-ankiwebserver-1 |     from anki.rsbackend import TR
anki-web-server-docker-ankiwebserver-1 |   File "/usr/local/lib/python3.8/site-packages/anki/rsbackend.py", line 28, in <module>
anki-web-server-docker-ankiwebserver-1 |     import anki.backend_pb2 as pb
anki-web-server-docker-ankiwebserver-1 |   File "/usr/local/lib/python3.8/site-packages/anki/backend_pb2.py", line 33, in <module>
anki-web-server-docker-ankiwebserver-1 |     _descriptor.EnumValueDescriptor(
anki-web-server-docker-ankiwebserver-1 |   File "/usr/local/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 755, in __new__
anki-web-server-docker-ankiwebserver-1 |     _message.Message._CheckCalledFromGeneratedFile()
anki-web-server-docker-ankiwebserver-1 | TypeError: Descriptors cannot not be created directly.
anki-web-server-docker-ankiwebserver-1 | If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
anki-web-server-docker-ankiwebserver-1 | If you cannot immediately regenerate your protos, some other possible workarounds are:
anki-web-server-docker-ankiwebserver-1 |  1. Downgrade the protobuf package to 3.20.x or lower.
anki-web-server-docker-ankiwebserver-1 |  2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
anki-web-server-docker-ankiwebserver-1 | 
anki-web-server-docker-ankiwebserver-1 | More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

**Comment by bootymcjudy** [comment]
I was able to resolve it by adding the line,
`protobuf~=3.19.0`
to the requirements.txt file in anki-web-server folder

**Comment by toyqiu** [comment]
> ```
> > docker-compose up -d
> Building ankisyncserver
> [+] Building 0.7s (9/13)                                                                                                  
>  => [internal] load build definition from Dockerfile                                                                 0.0s
>  => => transferring dockerfile: 37B                                                                                  0.0s
>  => [internal] load .dockerignore                                                                                    0.0s
>  => => transferring context: 2B                                                                                      0.0s
>  => [internal] load metadata for docker.io/library/python:3.8                                                        0.6s
>  => [1/9] FROM docker.io/library/python:3.8@sha256:c0fd64027a833c0caaf950ff6e4480d7cc1595991d9824f1114cd35765772b36  0.0s
>  => [internal] load build context                                                                                    0.0s
>  => => transferring context: 552B                                                                                    0.0s
>  => CACHED [2/9] RUN echo "init anki-sync-server"                                                                    0.0s
>  => CANCELED [3/9] ADD ankisyncd /app/ankisyncd                                                                      0.0s
>  => ERROR [4/9] ADD utils /app/utils                                                                                 0.0s
>  => ERROR [5/9] ADD ankisyncctl.py /app/ankisyncctl.py                                                               0.0s
> ------
>  > [4/9] ADD utils /app/utils:
> ------
> ------
>  > [5/9] ADD ankisyncctl.py /app/ankisyncctl.py:
> ------
> failed to compute cache key: "/ankisyncctl.py" not found: not found
> ERROR: Service 'ankisyncserver' failed to build : Build failed
> ```
> 
> System: macOS Montery, iMac with Intel CPU
> 
> How to Reproduce:
> 
> 1. Clone Repo
> 2. Execute ./init.sh in cloned repo
> 3. Execute docker-compose up -d



> You can go to anki-sync-server folder and get this specific [commit](https://github.com/ankicommunity/anki-sync-server/commit/43f4934de8add5f23aa9318a84c756f27214fb72) I am using.
> 
> ```
> git checkout 43f4934de8add5f23aa9318a84c756f27214fb72
> ```
> 
> Go to the docker-compose file, and rebuild the docker image then start
> 
> ```
> docker-compose build
> docker-compose up
> ```

the same issue
tried git checkout 43f4934de8add5f23aa9318a84c756f27214fb72
still not work
failed to compute cache key: "/ankisyncctl.py" not found: not found
